# Generated by Django 4.1.11 on 2023-12-10 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0017_remove_post_tag_remove_post_user_delete_comment_and_more'),
        ('smddpost', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.AddField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='smddapp.profile'),
        ),
    ]
