# Generated by Django 4.1.11 on 2023-12-10 06:24

from django.db import migrations, models
import smddpost.models


class Migration(migrations.Migration):

    dependencies = [
        ('smddpost', '0002_remove_post_user_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(blank=True, default='', related_name='tags', to='smddpost.tag'),
        ),
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, default='default_bg.png', null=True, upload_to=smddpost.models.user_directory_path, verbose_name='picture'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='post_title'),
        ),
    ]
