# Generated by Django 4.1.11 on 2023-12-10 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddpost', '0004_alter_post_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(blank=True, max_length=1000, null=True, verbose_name='post_title'),
        ),
    ]
