# Generated by Django 4.1.11 on 2023-12-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddpost', '0005_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Tag',
            field=models.ManyToManyField(blank=True, related_name='tags', to='smddpost.tag'),
        ),
    ]
