# Generated by Django 4.1.11 on 2023-12-28 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smddpost', '0011_remove_post_likes_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tag',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
