# Generated by Django 4.1.11 on 2023-12-07 23:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import smddapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0002_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=150)),
                ('profile_pic', models.ImageField(blank=True, default='default_profile.png', null=True, upload_to=smddapp.models.user_directory_path)),
                ('bg_pic', models.ImageField(blank=True, default='default_bg.png', null=True, upload_to=smddapp.models.user_directory_path)),
                ('bio', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('location', models.CharField(blank=True, max_length=100, null=True)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=13, null=True)),
                ('personal_intrests', models.CharField(blank=True, max_length=200, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profie_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
