# Generated by Django 4.1.11 on 2023-12-08 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0005_rename_user_follow_follow_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='follow_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
