# Generated by Django 4.1.11 on 2023-12-08 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0010_alter_follow_follower_alter_follow_following'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='follow',
        ),
    ]
