# Generated by Django 4.1.11 on 2023-12-08 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0014_remove_profile_follow_profile_follower_delete_follow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profie_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
