# Generated by Django 4.1.11 on 2023-12-09 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0016_alter_profile_follower'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Tag',
        ),
        migrations.RemoveField(
            model_name='post',
            name='user',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
