# Generated by Django 4.1.11 on 2023-12-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0018_remove_profile_username_remove_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(blank=True, default=' ', max_length=100, null=True),
        ),
    ]
