# Generated by Django 4.1.11 on 2024-07-02 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0021_alter_profile_birth_date_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='premium',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 7, 2, 12, 47, 33, 891882, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
