# Generated by Django 4.1.11 on 2024-09-19 06:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0022_user_premium_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='provider',
            field=models.CharField(default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 6, 5, 38, 831614, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
