# Generated by Django 4.1.11 on 2024-09-19 06:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0024_alter_profile_birth_date_alter_user_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 6, 28, 36, 942914, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
