# Generated by Django 4.1.11 on 2024-09-19 06:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smddapp', '0025_alter_profile_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 9, 19, 6, 32, 42, 453598, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='provider',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
